# -*- coding: utf-8 -*-
"""Proyecto M4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b6TGosj8Kz_Eojt_vpAciq6wapIW28Lg

#Proyecto M4 Ricardo López Degollado
SISTEMA DE PRÓNOSTICO DE TRÁFICO AÉREO BASADO EN DEEP LEARNING (LSTM)

##Paqueterías y modulos
"""

import os
import pandas as pd
import numpy as np

pd.set_option('display.float_format', lambda x: '%.5f' % x)

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns
import cufflinks as cf

cf.go_offline()

# Data Preprocessing
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

# Modeling – Deep Learning (LSTM)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# Models
from sklearn.linear_model import LinearRegression

#Metricas
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    mean_absolute_percentage_error
)
# Información
import kagglehub

# Download latest version
path = kagglehub.dataset_download("thedevastator/airlines-traffic-passenger-statistics")

print("Path to dataset files:", path)

for filename in os.listdir(path):
    print(filename)

Data = pd.read_csv(os.path.join(path, "Air_Traffic_Passenger_Statistics.csv"))

Data.head(5)

"""## EDA

### NULOS
"""

Data.info()

filtro_nan = Data['Operating Airline IATA Code'].isnull()

# 2. Aplicar el filtro al DataFrame para mostrar solo esas filas
registros_con_nan = Data[filtro_nan]

display(registros_con_nan.head(5))

Data = Data.dropna(subset=['Operating Airline IATA Code'])

Data = Data.dropna(subset=['Published Airline IATA Code'])

Data.info()

"""### Distribución de las Regiones"""

Data['GEO Region'].unique()

plt.figure(figsize=(10, 6))
sns.countplot(y='GEO Region', data=Data, order = Data['GEO Region'].value_counts().index, palette='viridis')
plt.title('Distribution of GEO Regions')
plt.xlabel('Count')
plt.ylabel('GEO Region')
plt.show()

Data['Year'].unique()

plt.figure(figsize=(10, 6))
sns.countplot(y='Year', data=Data, order = Data['Year'].value_counts().index, palette='viridis')
plt.title('Distribution of GEO Regions')
plt.xlabel('Count')
plt.ylabel('GEO Region')
plt.show()

"""### Actividad de los Pasajeros"""

Data['Activity Period'] = Data['Activity Period'].astype(str)
Data['YearMonth'] = pd.to_datetime(Data['Activity Period'], format='%Y%m')

Pasajeros = Data.groupby('YearMonth')['Adjusted Passenger Count'].sum().reset_index()

plt.figure(figsize=(15, 8))
sns.lineplot(x='YearMonth', y='Adjusted Passenger Count', data=Pasajeros)
plt.title('Historical Total Adjusted Passenger Count Per Month')
plt.xlabel('Date')
plt.ylabel('Adjusted Passenger Count')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

Data.head(5)

"""## Feature Engineering"""

Data['Trimestre'] = Data['YearMonth'].dt.quarter
display(Data.head())

Data['Mes'] = Data['YearMonth'].dt.month
Data['Mes']

"""### Codificación en Seno/Cos"""

Periodos = 12

Data['Month_Sin'] = np.sin(2 * np.pi * Data['Mes'] / Periodos)

Data['Month_Cos'] = np.cos(2 * np.pi * Data['Mes'] / Periodos)

plt.figure(figsize=(15, 8))
sns.lineplot(x='YearMonth', y='Month_Cos', data=Data)
plt.title('Month_Cos a lo largo del Tiempo')
plt.xlabel('Date')
plt.ylabel('Month_Cos Value')
plt.xticks(rotation=45)
plt.grid(True)
plt.tight_layout()
plt.show()

"""### Creación de variables

La intención es crear variables dummy en relación a eventos o estaciones importantes a lo largo del año que puedan involucar migración de pasajeros

Vacaciones de Verano - Spring Break - Navidad
"""

Nav = ['January', 'December']

Data['Nav'] = Data['Month'].isin(Nav).astype(int)

# Verificación de los resultados para el verano:
print(Data[['Month', 'Nav']].sample(20))

Meses = ['June', 'July', 'August']

Data['Verano'] = Data['Month'].isin(Meses).astype(int)

# Verificación de los resultados para el verano:
print(Data[['Month', 'Verano']].sample(20))

Data.info()

# 1. Agrupar por el período de actividad y sumar el conteo de pasajeros
df_ts = Data.groupby('Activity Period')['Passenger Count'].sum().reset_index()

# 2. Renombrar la nueva columna de suma a 'Total_Passengers'
df_ts.rename(columns={'Passenger Count': 'Total_Passengers'}, inplace=True)

# 3. Establecer el índice de tiempo (esto es opcional pero ayuda a las series de tiempo)
df_ts.set_index('Activity Period', inplace=True)

print("--- Primeros 5 registros de la nueva serie de tiempo 'Total_Passengers' ---")
print(df_ts.head())

Data = df_ts

lags = [1, 2, 3, 4, 6, 12]

for lag in lags:

    Data[f'Lag_{lag}M'] = Data['Total_Passengers'].shift(lag)

cols_to_scale = [col for col in Data.columns if col not in ['Activity Period', 'Is_Holiday_Season', 'Is_Summer_Peak', 'Is_Thanksgiving']]

scaler = MinMaxScaler()

Data[cols_to_scale] = scaler.fit_transform(Data[cols_to_scale])

# Definir el punto de corte (ej. usar el 80% de los datos para entrenamiento)
train_size = int(len(Data) * 0.8)
df_train = Data.iloc[:train_size]
df_test = Data.iloc[train_size:]

print(f"Tamaño de Entrenamiento: {len(df_train)} meses")
print(f"Tamaño de Prueba (Test): {len(df_test)} meses")

def build_lstm_sequences(df_data, n_steps):
    """
    Convierte un DataFrame 2D (con features y target) en secuencias 3D para la LSTM.
    ASUME que el target es la PRIMERA COLUMNA (índice 0).
    """
    X, y = [], []
    data = df_data.values
    target_index = 0 # El índice de la columna Total_Passengers

    for i in range(len(data) - n_steps):
        # X: Secuencia de n_steps filas (la ventana de lookback)
        seq_in = data[i:i + n_steps, :]

        # y: La etiqueta/objetivo (el valor del target en el paso de tiempo siguiente)
        seq_out = data[i + n_steps, target_index]

        X.append(seq_in)
        y.append(seq_out)

    return np.array(X), np.array(y)

target_col = 'Total_Passengers'
SEQUENCE_LENGTH = 12

# --- Reordenamiento para df_train ---
feature_cols_train = [col for col in df_train.columns if col != target_col]
column_order = [target_col] + feature_cols_train
df_train = df_train[column_order]

# --- Reordenamiento para df_test ---
feature_cols_test = [col for col in df_test.columns if col != target_col]
column_order = [target_col] + feature_cols_test
df_test = df_test[column_order]

print("Columnas de entrenamiento reordenadas. Target en la posición 0.")
print(df_train.head(1))

df_train.dropna(inplace=True)
df_test.dropna(inplace=True)

X_train, y_train = build_lstm_sequences(df_train, SEQUENCE_LENGTH)
X_test, y_test = build_lstm_sequences(df_test, SEQUENCE_LENGTH)

print("\n--- ¡Estructuración 3D completada! ---")
print(f"Forma de X_train (Muestras, Pasos de Tiempo, Características): {X_train.shape}")
print(f"Forma de y_train: {y_train.shape}")
print(f"Número de Características: {X_train.shape[2]}")

Data.info()

"""## Modelo LSTM"""

N_TIMESTEPS = X_train.shape[1]
N_FEATURES = X_train.shape[2]

model = Sequential()

model.add(LSTM(
    units=50,
    return_sequences=True,
    input_shape=(N_TIMESTEPS, N_FEATURES)
))

model.add(Dropout(0.3))

model.add(LSTM(units=50, return_sequences=False))
model.add(Dropout(0.3))

model.add(Dense(units=1))

# 1. Crear un optimizador con una tasa de aprendizaje
custom_adam = Adam(learning_rate=0.001)

# 2. Recompilar el modelo con el nuevo optimizador
model.compile(optimizer=custom_adam, loss='mean_squared_error')

"""###Summary"""

model.summary()

"""##Entrenamiento"""

history = model.fit(
    X_train, y_train,
    epochs=100,
    batch_size=32,
    validation_split=0.1,
    verbose=1
)

# 1. Verificar NaN en la matriz de features
nan_count_x = np.isnan(X_train).sum()
# 2. Verificar valores infinitos en la matriz de features
inf_count_x = np.isinf(X_train).sum()

# 3. Verificar NaN en el vector objetivo
nan_count_y = np.isnan(y_train).sum()
# 4. Verificar valores infinitos en el vector objetivo
inf_count_y = np.isinf(y_train).sum()


print(f"Total de valores NaN en X_train: {nan_count_x}")
print(f"Total de valores Inf en X_train: {inf_count_x}")
print(f"Total de valores NaN en y_train: {nan_count_y}")
print(f"Total de valores Inf en y_train: {inf_count_y}")

y_pred_normalizado = model.predict(X_test)

# 2. Reestructurar las predicciones para la des-normalización
# El scaler necesita una matriz 2D con TODAS las features, no solo el target 1D.

# Creamos una matriz que tenga la forma de X_test (sin la dimensión de timesteps)
# y rellenamos la primera columna (índice 0) con las predicciones normalizadas.
# Rellenamos el resto de columnas con ceros (o cualquier valor, ya que el scaler ignora su valor,
# pero necesita el espacio para invertir la transformación).
dummy_features = np.zeros((len(y_pred_normalizado), X_test.shape[2]))
dummy_features[:, 0] = y_pred_normalizado.flatten() # Colocamos la predicción normalizada en el índice 0

# 3. Aplicar la transformación inversa
# Esto convierte la matriz de vuelta a los valores originales (millones de pasajeros)
datos_predichos_invertidos = scaler.inverse_transform(dummy_features)

# 4. Extraer el valor des-normalizado del target (índice 0)
# ¡Esta es tu variable final para la validación!
y_pred_real = datos_predichos_invertidos[:, 0]

"""## Metricas"""

# Desnormalizar valores

dummy_y_test = np.zeros((len(y_test), X_test.shape[2]))
dummy_y_test[:, 0] = y_test.flatten() # Place the normalized y_test values in the first column

# Transformación Inversa para obtener el valor real de y_test values
y_test_real = scaler.inverse_transform(dummy_y_test)[:, 0]

# 2. Calcular las métricas
rmse = np.sqrt(mean_squared_error(y_test_real, y_pred_real))
mae = mean_absolute_error(y_test_real, y_pred_real)

def mape(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    return np.mean(np.abs((y_true - y_pred) / y_true)) * 100

mape_valor = mape(y_test_real, y_pred_real)

print(f"RMSE (Error en Pasajeros): {rmse:,.0f}")
print(f"MAE (Error Promedio): {mae:,.0f}")
print(f"MAPE (Error Porcentual): {mape_valor:.2f}%")

"""##Visualización"""

# --- 1. Obtener las Fechas (Índice) Correctas para el Eje X ---
SEQUENCE_LENGTH = 12
df_test_fechas = df_test.index[SEQUENCE_LENGTH:]


# 2. Crear el DataFrame para Graficar
df_plot = pd.DataFrame({
    'Fecha': df_test_fechas,
    'Tráfico Real': y_test_real,
    'Predicción LSTM': y_pred_real
})


# 3. Generar la Gráfica
plt.figure(figsize=(16, 7))

# Gráfico de los valores reales
plt.plot(df_plot['Fecha'], df_plot['Tráfico Real'],
         label='Tráfico Real',
         color='blue',
         linewidth=2)

# Gráfico de las predicciones del modelo
plt.plot(df_plot['Fecha'], df_plot['Predicción LSTM'],
         label='Predicción LSTM',
         color='red',
         linestyle='--',
         linewidth=2)

# Formato
plt.title('Tráfico de Pasajeros: Valores Reales vs. Predicción LSTM (Conjunto de Prueba)', fontsize=16)
plt.xlabel('Fecha', fontsize=12)
plt.ylabel('Pasajeros', fontsize=12)
plt.grid(True, linestyle=':', alpha=0.7)
plt.legend(fontsize=11)
plt.xticks(rotation=45)
plt.gca().ticklabel_format(style='plain', axis='y') # Evita notación científica en el eje Y
plt.tight_layout()
plt.show()



# --- 1. Preparar los datos para la gráfica ---

# Convertir las fechas del conjunto de prueba a formato datetime
df_test_fechas_dt = pd.to_datetime(df_test_fechas, format='%Y%m')

# Crear DataFrame para el tráfico real completo (entrenamiento + prueba)
df_full_real = Pasajeros.copy()
df_full_real.rename(columns={'Adjusted Passenger Count': 'Total_Passengers_Real'}, inplace=True)

# Crear DataFrame para las predicciones del conjunto de prueba
df_predictions = pd.DataFrame({
    'Fecha': df_test_fechas_dt,
    'Predicción LSTM': y_pred_real
})

# --- Se grafica -

plt.figure(figsize=(18, 8))

# Gráfico del tráfico real completo
plt.plot(df_full_real['YearMonth'], df_full_real['Total_Passengers_Real'],
         label='Tráfico Real Histórico',
         color='blue',
         linewidth=2)

# Gráfico de las predicciones del modelo (solo para el conjunto de prueba)
plt.plot(df_predictions['Fecha'], df_predictions['Predicción LSTM'],
         label='Predicción LSTM (Test Set)',
         color='red',
         linestyle='--',
         linewidth=2)

# Gráfico de los valores reales del conjunto de prueba (para comparación directa con la predicción)
plt.plot(df_predictions['Fecha'], y_test_real,
         label='Tráfico Real (Test Set)',
         color='green',
         linestyle=':',
         linewidth=2)

plt.title('Tráfico de Pasajeros: Historial Completo y Predicción LSTM', fontsize=18)
plt.xlabel('Fecha', fontsize=14)
plt.ylabel('Pasajeros', fontsize=14)
plt.grid(True, linestyle=':', alpha=0.7)
plt.legend(fontsize=12)
plt.xticks(rotation=45)
plt.gca().ticklabel_format(style='plain', axis='y') # Evita notación científica en el eje Y
plt.tight_layout()
plt.show()